# Universal imports

In [1]:
from google.colab import drive
import pandas as pd

In [2]:
# Import BERT-ready data from Gdrive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


# other git stuff

In [9]:
cd /content/gdrive/MyDrive/TechLabs/{repository}

/content/gdrive/MyDrive/TechLabs/ss23-drop-in-to-berlin


In [ ]:
!git branch KNN_classifier recommender

In [6]:
!git checkout KNN_classifier

M	keyword extraction.ipynb
Already on 'KNN_classifier'
Your branch is up to date with 'origin/KNN_classifier'.


In [10]:
!git remote set-url origin https://{git_token}@github.com/{username}/{repository}

In [11]:
!git branch

* KNN_classifier
  main
  recommender


In [9]:
!git config --global user.email "phylanx@gmx.de"
!git config --global user.name "phylanxy"

In [13]:
!git add .

In [14]:
!git commit -m "adding UMAP"

[KNN_classifier 8d6e773] adding UMAP
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite NN Classifier.ipynb (96%)


In [15]:
!git push

Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 15.12 KiB | 1.51 MiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/TechLabs-Berlin/ss23-drop-in-to-berlin
   4e7f604..8d6e773  KNN_classifier -> KNN_classifier


In [12]:
username = "TechLabs-Berlin"
repository = "ss23-drop-in-to-berlin"
git_token = ""

# Loading the data & data cleaning


In [16]:
df = pd.read_csv("/content/gdrive/MyDrive/Ironhack/Final_project/df_with_model_input_no_NaNs.csv")

In [17]:
# function to remove items specified in a list
def preprocess_input(string, lst_to_remove):
  for item in lst_to_remove:
    string = string.replace(item, "")
  if len(string.split()) < 4:
    string = None
  else:
    pass
  return string

# create a list to remove strings that don't carry meaning
remove_lst = ["'review0': ","'review1': ","'review2': ","'review3': ","'review4': ", "'editorial_summary':"]

In [18]:
# drop old indeces
df.drop(["Unnamed: 0", "Unnamed: 0.1"], inplace=True, axis=1)

In [19]:
# turn model input into the review text without the items specified in remove_lst
df["model_input"] = df["model_input"].apply(lambda x: preprocess_input(str(x), remove_lst) if x != None else "")

In [20]:
# drop NaNs from model_input col, otherwise embedding won't work later on
df.dropna(subset="model_input", inplace=True)

In [21]:
# convert everything into str, add empty string for anything that's not a string (keyBERT won't accept NaNs as input, but I want to preserve the order of the inputs, for correct assignemetn of the outputs to the corresponding rows)
# and then create a list of texts for keyBERT to process
BERTs = df["model_input"]

# use KNN on embeddings directly

In [ ]:
!pip install sentence_transformers

In [61]:
from sentence_transformers import SentenceTransformer
import pickle

In [27]:
# build sentence embeddings based on all-MiniLM-L6-v2
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
embeddings = model.encode(df["model_input"].to_numpy())

In [62]:
#Store reviews & embeddings on disc
with open('embeddings.pkl', "wb") as fOut:
    pickle.dump({'sentences': df["model_input"].to_numpy(), 'embeddings': embeddings}, fOut, protocol=pickle.HIGHEST_PROTOCOL)

In [48]:
embeddings.shape

(4273, 384)

In [49]:
# import stuff for NN algorithm
from sklearn.neighbors import NearestNeighbors
import numpy as np

In [50]:
# create a user input test
user_input = "This is really one of the most delicious vietnamnese restaurants I've ever seen. It tastes exacly like when my mom used to cook. Especially the Pho was incredible. Would always come back"
user_embedding = model.encode(user_input).reshape(1,-1)

In [51]:
user_embedding.shape

(1, 384)

In [52]:
# build NearestNeighbors model that finds the 20 nearest restaurants to the user input
nbrs = NearestNeighbors(n_neighbors=20, algorithm='ball_tree').fit(embeddings)
distances, indices = nbrs.kneighbors(user_embedding)

In [53]:
indices

array([[ 456, 3826, 1249, 3582,  163, 1262, 3907, 4014, 1084, 1291, 3165,
        1117, 3887,  878, 3964, 1789, 3621, 2701,  999, 1396]])

In [54]:
# flatten array to use as index in dataframe
indices = indices.flatten()

In [ ]:
# retrieve IDs of the restaurants to be sent to the app
df.iloc[indices]

## implement UMAP reducer to decrease dimensionality
## (this is not working -- aborting the experiment)

In [24]:
!pip install umap-learn

In [25]:
import umap.umap_ as umap

In [41]:
# define partial test vector for the embeddings
embs_test = embeddings[:100]

# fit and transform data using UMAP
reducer = umap.UMAP(n_components=10) # define reducer
umap_embs = reducer.fit_transform(embs_test) # return lower dimensionality vector

In [42]:
# create a user input test
user_input = "This is really one of the most delicious vietnamnese restaurants I've ever seen. It tastes exacly like when my mom used to cook. Especially the Pho was incredible. Would always come back"
user_embedding = model.encode(user_input).reshape(1,-1)
user_embs_umap = reducer.fit_transform(user_embedding)

In [43]:
umap_embs.shape, user_embs_umap.shape

((100, 10), (1, 10))

In [44]:
embs_test.shape

(100, 384)

In [45]:
# build NearestNeighbors model that finds the 20 nearest restaurants to the user input
nbrs = NearestNeighbors(n_neighbors=20, algorithm='ball_tree').fit(umap_embs)
distances, indices = nbrs.kneighbors(user_embs_umap)

In [46]:
distances, indices

(array([[17.99023126, 18.00834927, 18.01500212, 18.09331552, 18.14265953,
         18.16667835, 18.16842586, 18.19266265, 18.19817152, 18.25194706,
         18.25717969, 18.26244017, 18.27342963, 18.29504493, 18.29722028,
         18.30400719, 18.32640679, 18.48377698, 18.51090626, 18.53478569]]),
 array([[57, 36, 88, 78, 79, 73, 65, 45, 75, 86, 54, 31, 26, 62, 13, 93,
         66, 21, 49, 33]]))

In [47]:
df.iloc[indices.flatten()]

Unnamed: 0.2                                               name  \
57            57                    CaliBocca Restaurant & Wine Bar   
36            36                               Ristorante Portofino   
88            88                             Standard Serious Pizza   
78            78                                           Da Piada   
79            79                                       Vino e libri   
73            73                             Restaurant Via Nova II   
65            65                                           Da Vinci   
45            45                            Tiamo Restaurant berlin   
75            75                                    Viale dei Tigli   
86            86                                         Alimentari   
54            54                                        Sale e Pepe   
31            31                     Restaurant Trattoria Portofino   
26            26                          EIN BESONDERES RESTAURANT   
62            62                                            Dolcini   
13            13  Restaurant Machiavelli - Italienisches & Alpen...   
93            93                                             Donath   
66            66                                     Bocca di Bacco   
21            21                                 Restaurant Auszeit   
49            49                                   Asteria Köpenick   
33            33                                           Bellucci   

                      reference  \
57  ChIJ1Vrbe-RQqEcRnpasKjzVzTY   
36  ChIJJZExZt5QqEcReiy8E2SmySc   
88  ChIJB_FI3vxRqEcRheAWfledrdA   
78  ChIJrZ8OGuRRqEcRLGuMfehHnk0   
79  ChIJT9z_vvxRqEcRQvYDaqBLNS0   
73  ChIJD3C43txRqEcRosYHlSG8PSM   
65  ChIJNX291dxRqEcRUIJ_TyFnZL0   
45  ChIJ1wLfeL5aqEcRlAtXMWA8gfE   
75  ChIJ6wFH3MVRqEcRgOTx5SIY3Ys   
86  ChIJyRESH_tRqEcRcTrX03kcwG8   
54  ChIJ9_l59HBRqEcRlX-HAmUP6ps   
31  ChIJl8laNkNOqEcR_cP9hIHMPlE   
26  ChIJDxwnUmBPqEcR1mxWAXmC1zg   
62  ChIJJzE_OMVRqEcRj2kHQw7R2FA   
13  ChIJCal7aqZQqEcRS-dBiQO5RpY   
93  ChIJ4-fNA_1RqEcRCO8DFPl778A   
66  ChIJP5g9KttRqEcRFKxx7VlSTNA   
21  ChIJWwxJ0vBOqEcRj0SpaaXimjg   
49  ChIJN3sjK3BIqEcR3XYQNS3mgFQ   
33  ChIJNZ52e-hQqEcRhTkVAtxjL6w   

                                             geometry  \
57  {'location': {'lat': 52.5038995, 'lng': 13.316...   
36  {'location': {'lat': 52.50693949999999, 'lng':...   
88  {'location': {'lat': 52.532864, 'lng': 13.4086...   
78  {'location': {'lat': 52.5278283, 'lng': 13.400...   
79  {'location': {'lat': 52.5332028, 'lng': 13.406...   
73  {'location': {'lat': 52.51981, 'lng': 13.39222...   
65  {'location': {'lat': 52.5201506, 'lng': 13.391...   
45  {'location': {'lat': 52.4467753, 'lng': 13.343...   
75  {'location': {'lat': 52.5148883, 'lng': 13.381...   
86  {'location': {'lat': 52.5339432, 'lng': 13.401...   
54  {'location': {'lat': 52.5003888, 'lng': 13.336...   
31  {'location': {'lat': 52.5123147, 'lng': 13.448...   
26  {'location': {'lat': 52.4884947, 'lng': 13.461...   
62  {'location': {'lat': 52.5138203, 'lng': 13.386...   
13  {'location': {'lat': 52.4748257, 'lng': 13.278...   
93  {'location': {'lat': 52.5339085, 'lng': 13.409...   
66  {'location': {'lat': 52.5151203, 'lng': 13.388...   
21  {'location': {'lat': 52.5051816, 'lng': 13.469...   
49  {'location': {'lat': 52.4470855, 'lng': 13.575...   
33  {'location': {'lat': 52.499467, 'lng': 13.3067...   

                                    formatted_address  price_level  rating  \
57           Schlüterstraße 30, 10629 Berlin, Germany          2.0     4.6   
36               Kantstraße 63, 10627 Berlin, Germany          2.0     4.2   
88            Templiner Str. 7, 10119 Berlin, Germany          2.0     4.3   
78            Auguststraße 49A, 10119 Berlin, Germany          NaN     4.0   
79            Choriner Str. 72, 10119 Berlin, Germany          2.0     4.5   
73        Universitätsstraße 2, 10117 Berlin, Germany          2.0     4.1   
65           Georgenstraße 192, 

# code snippets

In [ ]:
#Load sentences & embeddings from disc
with open('embeddings.pkl', "rb") as fIn:
    stored_data = pickle.load(fIn)
    stored_sentences = stored_data['sentences']
    stored_embeddings = stored_data['embeddings']